### ISSUE TITLE
Dashes in file name crash during drawing

### ISSUE THREAD

**Issue by rbutleriii** [mjsull/Easyfig#4]
I didn't see it in the manual, but it should be noted that dashes in file names will produce the following error. Running .exe on Win10.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\mjsul_000\Documents\GitHub\build\Easyfig\out00-PYZ.pyz\threading", line 810, in __bootstrap_inner
  File "C:\Users\mjsul_000\Documents\GitHub\build\Easyfig\out00-PYZ.pyz\threading", line 763, in run
  File "<string>", line 9732, in makeFigure2
  File "<string>", line 6913, in drawsvg
  File "<string>", line 5729, in getArrows
ValueError: need more than 1 value to unpack

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\mjsul_000\Documents\GitHub\build\Easyfig\out00-PYZ.pyz\threading", line 810, in __bootstrap_inner
  File "C:\Users\mjsul_000\Documents\GitHub\build\Easyfig\out00-PYZ.pyz\threading", line 763, in run
  File "<string>", line 9701, in dotdotdot
AttributeError: App instance has no attribute 'theminblast'

**Comment by mjsull** [comment]
Hi,

Sorry for taking so long to get back to you. Had some trouble finding a windows 10 machine to test this, and then when I did the problem only seemed to appear half the time.

I've heard that the new version of blast seems to have some problems with relative directories (i.e. it needs the full path). I've created a fix and will test it out tonight and update if it fixes the problem.

-Mitch

**Comment by mjsull** [comment]
I've updated the current github version to use absolute paths. Hopefully this solves the problem (I am now completely unable to recreate it using the old version). It may have been fixed in more recent BLAST+ releases. I'll update the binaries tonight.

**Comment by yifangt** [comment]
Not sure this is an issue as I am not familiar with python. To seek some help to get it run in my Debian machine, the error message is:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Easyfig.py", line 9733, in makeFigure2
    self.minmaxlist, self.autodetect.get() == 1, self.theleg, self.legname.get())
  File "Easyfig.py", line 6025, in draw
    temp = getArrows(inputlist[i], legname)
  File "Easyfig.py", line 5914, in getArrows
    theseq = theseq.replace('qqq', 'n' * (len(theseq) / 500))
MemoryError

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Easyfig.py", line 9713, in dotdotdot
    if self.theminblast == 101:
AttributeError: App instance has no attribute 'theminblast'
```

Any help is greatly appreciated.
-Yifang

**Comment by mjsull** [comment]
Hi Yifang,

Sorry for taking so long, it seems github has been pretty poor alerting me to outstanding issues. It seems the length of the FASTA file being used is much too large for Easyfig to use and it's causing a memory issue on your computer.

-Mitch

**Comment by yifangt** [comment]
Thanks a lot!
That's explains quite a lot thing, and I will try it again with some modification accordingly.

Yifang
