### ISSUE TITLE
theminblast error from binary run on Linux 

### ISSUE THREAD

**Issue by yifangt** [mjsull/Easyfig#7]
Not sure this is an issue as I am not fluent with python. To seek help to get it run in my Debian machine.
Same error message with both ran from source code and binary, which is:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/mjsull/scripts/build/Easyfig/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/home/mjsull/scripts/build/Easyfig/out00-PYZ.pyz/threading", line 763, in run
  File "<string>", line 9721, in makeFigure2
  File "<string>", line 6029, in draw
  File "<string>", line 5918, in getArrows
MemoryError

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/mjsull/scripts/build/Easyfig/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/home/mjsull/scripts/build/Easyfig/out00-PYZ.pyz/threading", line 763, in run
  File "<string>", line 9701, in dotdotdot
AttributeError: App instance has no attribute 'theminblast'

```
Any help is greatly appreciated.
-Yifang

**Comment by mjsull** [comment]
Hi Yifang,

You probably need to run Easyfig on a system with more memory,

Best,

Mitch
